sudo: false
language: scala
jdk:
- openjdk8
- openjdk11
script:
- git clone https://github.com/gitbucket/gitbucket.git
- cd gitbucket
- sbt publishLocal
- cd ../
- sbt test
addons:
  apt:
    packages:
    - oracle-java8-installer
